name = "Nneoforoge"
author = "gaura"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "419cddb53421f2636b62b8997b9e77cb59939c92f656d95609202714cabcd39d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"
