#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 11 21:08:54 AEST 2026
allowUnknownShaders=false
colorSpace=DISPLAY_P3
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Mellow Shader v3.1.zip
