version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
tide = true
mcwfences = true
farmersdelight = true
create_new_age = true
mcwwindows = true
someassemblyrequired = true
wither_spawn_animation = true
piglinproliferation = true
ribbits = true
galosphere = true
easyanvils = true
aether_enhanced_extinguishing = true
natures_spirit = true
irons_spellbooks = true
veggiesdelight = true
comforts = true
create_enchantment_industry = true
aether = true
spring_to_life = true
benssharks = true
mcwbridges = true
fastpaintings = true
amendments = true
createcobblestone = true
lolmcv = true
moonlight = true
biomesoplenty = true
wilderflowers = true
mushroomquest = true
deeperdarker = true
create = true
createcasing = true
yungscavebiomes = true
deep_aether = true
create_deep_dark = true
rottencreatures = true
visualworkbench = true
fungidelight = true
minecraft = true
animal_feeding_trough = true
create_dragons_plus = true
lootr = true
create_wizardry = true
sliceanddice = true
thirst = true
endermanoverhaul = true
waystones = true
dragonlib = true
creeperoverhaul = true
irons_patreon_lib = true
rocks = true
realmrpg_skeletons = true
crittersandcompanions = true
createsifter = true
netherdepthsupgrade = true
expandeddelight = true
meadow = true
